require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AsciiComments:
  Enabled: false
